server:
  port: 8084

spring:
  application:
    name: barriodigital-ms-audit

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: barriodigital
    password: barriodigital
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ms-audit-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer